### ISSUE TITLE
Need option added to enable SSL in SubscriptionServiceImplementation.cs

### ISSUE THREAD

**Issue by goetzcj** [ringcentral/ringcentral-csharp#15]
Worked with PubNub support to nail down an issue that occurs when devices are behind a proxy that is not within our control.  The issue was that the subscription would connect but would throw a "`Gateway timeout`" error exactly 60 seconds later.  The proxy was actually returning this error on behalf of PubNub instead of waiting on the response.  Enabling the SSL option fixed the issue.  Specifically referencing the `RingCentral.NET40` code.  As a side note we noticed that the `_pubnub` object was being collected by GC after simulating a user staying logged in for long periods of time without activity.  The example code below shows how we worked around it but it may not be the perfect fix.

Added a public property to the class and set the default to false:

```cs
public bool enableSSL { get; set; } = false;

private void PubNubServiceImplementation(string publishKey, string subscribeKey)
    {
        //_pubnub = new Pubnub(publishKey, subscribeKey);
        _pubnub = new Pubnub(publishKey, subscribeKey, "", "", enableSSL);
        GC.KeepAlive(_pubnub);
    }
    
public void PubNubServiceImplementation(string publishKey, string subscribeKey, string secretKey,string cipherKey,bool sslOn)
    {
        //_pubnub = new Pubnub(publishKey,subscribeKey);
        _pubnub = new Pubnub(publishKey, subscribeKey, "", "", enableSSL);
        _encrypted = true;
        var aes = new AesManaged {Key = Convert.FromBase64String(cipherKey), Mode = CipherMode.ECB, Padding = PaddingMode.PKCS7};
        _decrypto = aes.CreateDecryptor();
        GC.KeepAlive(_pubnub);
    }
```

**Comment by grokify** [comment]
Thanks for reporting this. We are working on resolving this and will provide an update when available.

**Comment by nrobison** [comment]
Thanks for your suggestions! If you checkout the develop branch you will see we added two methods. You can also check these changes work for you by installing the prerelease version of the package through Nuget. The current prerelease package is up to date with the develop branch. 


`SubscriptionServiceImplementation subscription =  new SubscriptionServiceImplementation(){_platform = Platform};`
`subscription.EnableSSL(true);`
Also you can check if SSL is enabled by
`bool isSSL = subscription.IsSSL()`
 
Now we can check for SSL flag when creating Pubnub objects.

```
    private void PubNubServiceImplementation(string publishKey, string subscribeKey)
		{
		    if (_enableSSL) _pubnub = new Pubnub(publishKey, subscribeKey, "", "", _enableSSL);
		    else _pubnub = new Pubnub(publishKey, subscribeKey); 
		    GC.KeepAlive(_pubnub);
		}
       
        public void PubNubServiceImplementation(string publishKey, string subscribeKey, string secretKey,string cipherKey)
		{
			_pubnub = new Pubnub(publishKey,subscribeKey,secretKey,cipherKey,_enableSSL);
			_encrypted = true;
			_decrypto = new  PubnubCrypto(cipherKey);
            GC.KeepAlive(_pubnub);
            GC.KeepAlive(_decrypto);
        }
```
