### ISSUE TITLE
Whats the status of the develop branch?

### ISSUE THREAD

**Issue by erichexter** [ringcentral/ringcentral-csharp#2]

**Comment by grokify** [comment]
The code in the develop branch is currently available on NuGet.org as RingCentralSDK 0.0.35.

We are performing a final review to consider merging this into the master branch.

**Comment by erichexter** [comment]
Will there be sample or a documentation site to accompany the sdk? I am
particularly interested in automating call routing based on inbound calling
number.

On Wednesday, September 23, 2015, John Wang <notifications@github.com>
wrote:

> The code in the develop branch is currently available on NuGet.org as
> RingCentralSDK 0.0.35.
>
> We are performing a final review to consider merging this into the master
> branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ringcentral/ringcentral-csharp/issues/2#issuecomment-142765165>
> .
>


-- 
Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by grokify** [comment]
Sample documentation for SDK is included in the README.md file at the root of the repo. You can see this in the develop branch at the moment.

The API doesn't yet support automating call routing based on inbound calling number yet. This is something that we are looking to provide in an upcoming release. If you email us at devsupport@ringcentral.com we can discuss whether our upcoming plans can address your use case.
