### ISSUE TITLE
Setting subscriptions aggregated query parameter to true using the c#.net SDK

### ISSUE THREAD

**Issue by moody550** [ringcentral/ringcentral-csharp#21]
In the API Docs, it states if you want the subscription to return certain parameters, lets say, dndStatus on a Presence event, the aggregated query parameter on the subscription request need to be set to true. I am unable to see where you can set this parameter to true using the c# .NET SDK. Is this not a option using the SDK?

**Comment by tylerlong** [comment]
Let me check and get back to you later. Stay tuned.

**Comment by tylerlong** [comment]
For query parameters, just append them to the request url, such as:

```
/restapi/v1.0/account/~/extension/~/presence?aggregated =true
```

Please let me know whether it works for you.

**Comment by moody550** [comment]
That worked. Much appreciated. I will share your solution on the RingCentral forum thread I created.

Regards
