### ISSUE TITLE
PubNub Subscription Connection - Amazon AWS calls?

### ISSUE THREAD

**Issue by moody550** [ringcentral/ringcentral-csharp#23]
In our environment, we have a Palo Alto firewall that monitors traffic to determine which internet circuit to send traffic out of. For example, all voice traffic and ringcentral traffic is set to go out a specific circuit and all internet browsing goes out another. My problem arises when my app tries to subscribe while this advanced policy based forwarding is turned on. What happens is that call to subscribe to the events happens, it goes out internet connection A, but the SDK makes a call to Amazon AWS for some reason, and that traffic goes out connection B. The mismatch on circuits causes the subscription to error out with: " The underlying connection was closed."

How I can fix this problem is by telling the firewall to route all of theses requests to go out the same circuit/internet connection. The problem is, I do not have a list of DNS addresses that it is looking for and the IP changes for Amazon AWS. Is there a way someone can tell me what DNS addresses or what IP range the app is connecting to so that I can make theses changes on my firewall?

I have tested the app with policy based forwarding turned off, forcing all traffic to go out one connection, the subscription works fine and as expected.

This may seem confusing, if you need clarification on something let me know.

Thanks

**Comment by tylerlong** [comment]
I am currently checking this issue. Although I am not sure, I think the AWS request is made by the PubNub code which RingCentral SDK has no direct control. I will get back to you later.

**Comment by tylerlong** [comment]
I did some investigation about pubnub and I found two domain names: `push.pubnub.com`, `ps1.pubnub.com`. Can you configure the forwarding policy based on domain name `*.pubnub.com` ?

I also found this thread relevant: https://www.pubnub.com/knowledge-base/discussion/205/can-i-whitelist-ips-for-pubnub-traffic

**Comment by moody550** [comment]
I had to reach out to PubNub support for a IP whitelist and that has solved this issue.

Thanks
