### ISSUE TITLE
SubscriptionServiceImplementation.IsSubsribed should be IsSubscribed

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-csharp#3]
The method `IsSubsribed()` should be `IsSubscribed()`. This is present in:

1. `RingCentral.Android/SubscriptionServiceImplementation.cs`
1. `RingCentral.NET40/SubscriptionServiceImplementation.cs`
1. `RingCentral.iOS/SubscriptionServiceImplementation.cs`

**Comment by nrobison** [comment]
All ```IsSubsribed()``` corrected to ```IsSubscribed()```. Changes present in NuGet package 0.0.39 and above.
