### ISSUE TITLE
Document the behavior of `Subscription` instance

### ISSUE THREAD

**Issue by LingForCC** [ringcentral/ringcentral-csharp#35]
Since user needs to main the lifecycle of `Subscription` instance by themselves, we should provide detail info regarding this in README to avoid unexpected behavior.

**Comment by tylerlong** [comment]
I write some code here: https://github.com/ringcentral/ringcentral-csharp/commit/173bf60192473e17c012baace56e7b7f43d6c9d5

**Comment by tylerlong** [comment]
Done and published to readthedocs.
