### ISSUE TITLE
Suggestion: async

### ISSUE THREAD

**Issue by dariusdamalakas** [ringcentral/ringcentral-csharp#38]
Kudos for great work, i like the minimalistic approach. 

One thing i've missed though was `async` support, blocking calls [should be avoided](https://github.com/ringcentral/ringcentral-csharp/blob/master/RingCentral/Platform/Platform.cs#L119). Perhaps something for 1.1.0 release.

**Comment by grokify** [comment]
@dariusdamalakas Thanks for the note. Auth is a special area because we don't want to have API calls being sent with an expired or invalid token while an authorization flow is in progress. We'll look into what we can do here.

**Comment by dariusdamalakas** [comment]
@grokify , auth is tricky challenge, especially as you invalidate previously issued `access_tokens` (docs [claim that](https://developer.ringcentral.com/api-docs/latest/index.html#!#RefreshTokenFlow), and i've run a simple demo to check this is true). There is no way for the client to know if the current `access_token` is still valid or not, as using a `refresh_token` to obtain a new token pair invalidates the previously issued `access_token`. 

So in essence the [IsAccessToken](https://github.com/ringcentral/ringcentral-csharp/blob/master/RingCentral/Platform/Auth.cs#L232) method does not actually do what is says. Itonly checks the `ttl` (refresh_token_expires_in) value, but the token might be already invalidated by the authorization server. I guess the only way to check if `access_token` is still valid is to hit some API endpoint.

**Comment by tylerlong** [comment]
I think it is a good suggestion to support `async`. 

For auth, if token is invalidated from server side, the client won't be notified. Currently client code needs to catch exceptions about auth and obtain new token again.

**Comment by grokify** [comment]
It is a good idea to support `async`. Our JS SDK supports it.

@tylerlong It would be good to check with @kirill-konshin on the JS SDK to coordinate efforts.

**Comment by tylerlong** [comment]
We have another repository which supports full async: https://github.com/ringcentral/ringcentral-csharp-client
