### ISSUE TITLE
ApiResponse internal constructor

### ISSUE THREAD

**Issue by dariusdamalakas** [ringcentral/ringcentral-csharp#40]
Any chance `ApiResponse` constructor could be made back to public? [source](https://github.com/ringcentral/ringcentral-csharp/blob/master/RingCentral/Http/ApiResponse.cs#L14).  This has caused a massive regression issue for us after updating to 1.0.0. There are a lot of unit-tests mocking SDK client responses, and now we can't construct any new `ApiResponse` instances.

**Comment by tylerlong** [comment]
I changed it to internal because I didn’t think it should be initialised outside. 

Public classes/methods/variables are contracts you signed with outside world. They should be as minimal as possible. I changed quite a lot of “public” to “private/internal” in 1.0.0.

But it seems that creating mock objects outside for testing purpose is also reasonable. **Let me think about it further and get back to you later**.

At current moment, I suggest that you install the previous version to fix issues temporarily: `Install-Package RingCentralSDK -Version 0.1.21`

**Comment by dariusdamalakas** [comment]
@tylerlong , thanks. To be fair, i would love to see more abstractions and extension points in the SDK. Specifically, here is what I am thinking of:
 * `Platform` might have an interface. This would allow to easily mock `IPlatform` or `ISdk` in our unit tests. 
 * Provide a hook to control `access_token` refresh lifecycle.  

I have already contacted @bdeanindy for input on this. We have a background service which subscribes for presence notification events. The tokens are acquired via UI using `code` grant (3-legged-auth), and are passed to the background job. 

The issue comes when subscription renewal loop ([this code](https://github.com/ringcentral/ringcentral-csharp/blob/master/RingCentral/Subscription/SubscriptionService.cs#L105)) acquires a new token pair if current `access_token` is expired. At the moment there is no way how we can detect when this refresh happens and persist new token pair in our storage. We store auth tokens in the storage, so that the background process would survive restarts. We don't want to lose `refresh_token` and then contact user to ask him to log in again.

As for upgrading to version `0.1.21`, that version has the same issue (see [this line](https://github.com/ringcentral/ringcentral-csharp/blob/0.1.21/RingCentral/platform/Auth.cs#L145)).

**Comment by tylerlong** [comment]
@dariusdamalakas  Access to `ApiResponse` contructor is not mandatory to write mock tests.

Take our [RingCentral.Test.Mock](https://github.com/ringcentral/ringcentral-csharp/tree/master/RingCentral.Test.Mock) project for example. It's in a separate assembly from RingCentral SDK. It doesn't have access to `ApiResponse` contructor. And we are still able to create mock responses.

Please check these two files for how we do it:

- https://github.com/ringcentral/ringcentral-csharp/blob/c9d21388cd3b4436fba26fb89bfccb2803165ef7/RingCentral.Test.Mock/BaseTest.cs#L25
- https://github.com/ringcentral/ringcentral-csharp/blob/c9d21388cd3b4436fba26fb89bfccb2803165ef7/RingCentral.Test.Mock/MockHttpClient.cs

**Comment by dariusdamalakas** [comment]
@tylerlong thanks, that's a good way to mock that. I'll see how easy is to retrofit our unit tests to use this.

Any ideas/suggestions on getting hold of newly acquired tokens, which your platform is doing silently if current token is expired?

**Comment by tylerlong** [comment]
@dariusdamalakas This thread is only for the internal constructor issue. I created a new one to track token management issues: https://github.com/ringcentral/ringcentral-csharp/issues/43

**Comment by dariusdamalakas** [comment]
@tylerlong thanks.   I guess we can close this, using `DelegatingHandler` is good enough way to mock responses.
