### ISSUE TITLE
Approach for VB.NET docs

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-csharp#42]
There are some VB.NET users that can utilize the C# SDK so it would be nice to provide docs for these users.

Some approaches are:
1. Combined C# and VB.NET docs
2. Separate ReadTheDocs project for VB.NET

Desirability of choices may depend on [whether Mkdocs and Sphinx support tabbed code blocks](http://stackoverflow.com/questions/37606292/how-to-create-tabbed-code-blocks-in-mkdocs-or-sphinx).

A separate ReadTheDocs project can also be in a separate GitHub repo if this would be the best approach.

Here's some working VB.NET example code that was developed for a RingCentral community request:

https://gist.github.com/grokify/2c32b06e885b4637b8153a4b938fccb6

**Comment by tylerlong** [comment]
Can we just include this link into our docs: http://converter.telerik.com/ ?

**Comment by grokify** [comment]
It would be great to just link to Telerik but I tried it earlier and the generated code (which you also posted) doesn't build for me on Visual Studio Community 2015. Were you able to build and run it successfully?

I get the following:

| Severity | Code | Description |
|------------|--------|----------------|
| `Error` | `BC32022` | `'Public Event ConnectEvent As EventHandler(Of SubscriptionEventArgs)' is an event, and cannot be called directly. Use a 'RaiseEvent' statement to raise an event.` |

If you were able to successfully build and run the code pasted above, let's compare notes. If not, are there other code converters that work better?

**Comment by tylerlong** [comment]
No I didn't try it at all. I have little experience with VB.

I just had a quick try and it turned out to be not working.

It seems that converter from telerik cannot convert lambda event handlers correctly.  The following does compile: 

```vb
Dim subscription = sdk.CreateSubscription()
subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/message-store")
subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence")

AddHandler subscription.ConnectEvent, Sub(sender, args)
                                          Console.WriteLine("Connected:")
                                          Console.WriteLine(args.Message)
                                      End Sub
AddHandler subscription.NotificationEvent, Sub(sender, args)
                                               Console.WriteLine("Notification:")
                                               Console.WriteLine(args.Message)
                                           End Sub
AddHandler subscription.ErrorEvent, Sub(sender, args)
                                        Console.WriteLine("Error:")
                                        Console.WriteLine(args.Message)
                                    End Sub

subscription.Register()
```

**Comment by tylerlong** [comment]
Nope, I cannot find any more online converters. This one seems to be broken: http://www.developerfusion.com/tools/convert/csharp-to-vb  

We have to do it the hard way.

**Comment by grokify** [comment]
One option is to hold off on formal VB docs until we have Slate to keep multi-language support there. Until then, we have the Gist above we can provide when asked. This way we can keep focused on our core multi-language doc efforts.

**Comment by grokify** [comment]
I'm closing this because there doesn't seem to be a lot of need for this.
