### ISSUE TITLE
Csharp console application  response error  kindly check your Code 

### ISSUE THREAD

**Issue by addikhann** [ringcentral/ringcentral-csharp#48]
we tried to run your code (console C Sharp code) but it gave error in response. we also asked your support team but in vain. below is the code for our API ..

Company name: Marsden Smart Cars
platform.login("number", "extension", "Password”);

var sdk = new SDK("", ", "https://platform.devtest.ringcentral.com/", "1", "1");
            var platform = sdk.GetPlatform();
            Response response = platform.Authorize("", "", "", true);

below is the link you guys provided..... but its not working.
https://github.com/vyshakhbabji/ringcentral-csharp-demo/blob/master/ConsoleApplication1/Program.cs

my email id is
adeel4_2003@hotmail.com

**Comment by tylerlong** [comment]
Hi @addikhann,

The demo code https://github.com/vyshakhbabji/ringcentral-csharp-demo/blob/master/ConsoleApplication1/Program.cs is based on an old version of the C# SDK.

For the latest SDK (1.0.1), please refer to the documentation: http://ringcentral-csharp.readthedocs.io/en/latest/

If you still have issues, please kindly provide me with the error messages and stack traces.

**Comment by addikhann** [comment]
can you please tell me how to use this because its does not response , i am calling this but its response in error

**Comment by tylerlong** [comment]
Sample code is available here: http://ringcentral-csharp.readthedocs.io/en/latest/

If you want more help please provide me with more information. Such as: your code, detailed error messages...etc.  For now I really have no idea why it does not respond because you didn't tell me any detail.

**Comment by addikhann** [comment]
private void button1_Click(object sender, EventArgs e)
        {
            string path = @"D:\log.txt";
            Platform obje = new Platform(" ", "Application Secret", "https://platform.devtest.ringcentral.com", "Treasure", "");
            var ss = obje.Login("", "301", "", true);
            File.WriteAllText(path, ss.ToString());
       
        }


An unhandled exception of type 'System.IO.FileLoadException' occurred in WindowsRingCentral.exe

Additional information: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by addikhann** [comment]
can you please send your offical email address i am send you my code

**Comment by tylerlong** [comment]
Please send to tyler.liu@ringcentral.com and I will check it tomorrow morning (It is midnight in my local time).

**Comment by addikhann** [comment]
ok dear

**Comment by tylerlong** [comment]
I am reading your code. I will post updates here:

First of all, we recommend installation of RingCentral SDK via NuGet. If you install it manually, you also need to install all its dependencies which is tedious and error prone (for example, in your message above, you mentioned the missing of Newtonsoft.Json).  Here is how you can install RingCentral SDK via NuGet.

Inside Visual Studio, menu -> Tools -> NuGet Package Manager -> Package Manager Console

Execute command: Install-Package RingCentralSDK

Or if you prefer GUI: Inside Visual Studio, menu -> Tools -> NuGet Package Manager -> Manager NuGet Packages for Solution...

**Comment by tylerlong** [comment]
I've found two minor issues in your code.

Here is how we get a `Platform` instance:

```cs
var sdk = new SDK("app key", "app secret", SDK.Server.Sandbox, "app name", "app version");
var platform = sdk.Platform;
```


When you call the `Login` method, if your username is a direct number, just left the extension as empty string:

```cs
platform.Login("direct number", "", "password", true);
```

I've got your code working and sent it back to you.

Please let me know if you need any more help. :smile:

**Comment by addikhann** [comment]
it respond in "access_token"  but i want Caller ID which can give me response and also show the caller's number in my application. Where can I enter this access token to get caller ID?

**Comment by tylerlong** [comment]
What do you mean by "caller ID"?  Who is calling? What is the caller while who is the callee?

**Comment by addikhann** [comment]
CALLER ID: when the CRM receive calls, we fetch that data and make it available in our software so every calls come like pop ups in our software

**Comment by tylerlong** [comment]
You need subscription API: http://ringcentral-csharp.readthedocs.io/en/latest/usage/notifications/Subscriptions/


```cs
var subscription = sdk.CreateSubscription();
subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence");

subscription.NotificationEvent += (sender, args) => {
    Console.WriteLine(args.Message); 
};

subscription.Register();
```

**Comment by addikhann** [comment]
its connected... but when i call event not fire...

**Comment by addikhann** [comment]
var subscription = sdk.CreateSubscription();
            subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/message-store");
            subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence");
            subscription.ConnectEvent += subscription_ConnectEvent;   
            subscription.NotificationEvent += subscription_NotificationEvent; 
            subscription.Register();

   void subscription_ConnectEvent(object sender, RingCentral.Subscription.SubscriptionEventArgs e)
        {
            MessageBox.Show(sender.ToString());
            MessageBox.Show(e.Message.ToString());// throw new NotImplementedException();
        }

        void subscription_NotificationEvent(object sender, RingCentral.Subscription.SubscriptionEventArgs e)
        {
            MessageBox.Show(sender.ToString());
            MessageBox.Show(e.Message.ToString());
        }

        void subscription_ErrorEvent(object sender, RingCentral.Subscription.SubscriptionEventArgs e)
        {
            MessageBox.Show(sender.ToString());
            MessageBox.Show(e.Message.ToString());
        }

**Comment by addikhann** [comment]
when we are dialing your given number it is not dialing through
kindly provide us the valid number with country and area postcode

**Comment by tylerlong** [comment]
What do you mean by "your given number"?

> subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/message-store");

This is for messages(such as SMS), not for calls. You can remove it if you don't need messages event.

> its connected... but when i call event not fire...

You need to call the correct number. If you are monitoring `/account/~/extension/~`, the tilde symbol (~) means account/extension that you are currently logged in to.

**Comment by addikhann** [comment]
how to call on sandbox number ?

**Comment by addikhann** [comment]
is it ok ?  subscription.EventFilters.Add("/restapi/v1.0/account/~/101/~/");

**Comment by tylerlong** [comment]
Sorry for the late reply. I went to bed after my last message.

Unfortunately I am not an export for account administration. The testing numbers I use are setup by someone else.

I think you need to login https://service.devtest.ringcentral.com/ to lookup/setup your direct phone numbers.

Maybe let me find someone else to help.

**Comment by tylerlong** [comment]
@LingForCC @grokify Could you please help on this?

**Comment by addikhann** [comment]
Can you please tell me how to test Sandbox account because in my Sandbox Environment show this 15183483039 number and i am calling  this number   subscription.NotificationEvent not fired ,  how to change my Account Environment  Sandbox Environment to Production Environment, because its too late for me, i want Production Environment.

**Comment by tylerlong** [comment]
How to change sandbox environment to production environment is out of scope of this project. You are asking question in the wrong place.

I am afraid it's not a technical question, it's a business question instead. At least there is no such API call that I am aware of which can turn your app into production.

Could you please ask your question here: https://community.ringcentral.com/ringcentral?topic-list[settings][type]=recent ?

I would like to have this issue closed because the original issue `Csharp console application response error` had been resolved.

Feel free to create a new issue if you have questions about the C# SDK.

**Comment by addikhann** [comment]
@tylerlong   Can you please tell me how to test Sandbox account because in my Sandbox Environment show this 15183483039 number and i am calling this number subscription.NotificationEvent not fired. is C# SDK problem

**Comment by tylerlong** [comment]
@addikhann OK, let's create a new issue to track it: https://github.com/ringcentral/ringcentral-csharp/issues/50
