### ISSUE TITLE
No notification in sandbox environment.

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-csharp#50]
From @addikhann:

> Can you please tell me how to test Sandbox account because in my Sandbox Environment show this 15183483039 number and i am calling this number subscription.NotificationEvent not fired. is C# SDK problem

**Comment by addikhann** [comment]
Can you please tell me how to test Sandbox account because in my Sandbox Environment show this 15183483039 number  i am calling this number and dial extension 101 subscription.NotificationEvent not fired. is C# SDK problem

**Comment by addikhann** [comment]
var sdk = new SDK("", "", SDK.Server.Sandbox, "", "1.0.0");
            var platform = sdk.Platform;
            var response = platform.Login("", "", "", true);
       
            var subscription = sdk.CreateSubscription();
    subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence?detailedTelephonyState=true");
 subscription.ConnectEvent += subscription_ConnectEvent;    
            subscription.NotificationEvent += subscription_NotificationEvent;    
            subscription.Register();
  void subscription_ConnectEvent(object sender, RingCentral.Subscription.SubscriptionEventArgs e)
        {
           // var message = ((JObject)e.Message).SelectToken("body.changes[0].type").ToString();
            MessageBox.Show(sender.ToString());
            MessageBox.Show(e.Message.ToString());// throw new NotImplementedException();
        }

        void subscription_NotificationEvent(object sender, RingCentral.Subscription.SubscriptionEventArgs e)
        {
            MessageBox.Show(sender.ToString());
            MessageBox.Show(e.Message.ToString());
        }

**Comment by tylerlong** [comment]
The following code works for me:

```cs
using System;
using System.Threading;
using RingCentral;
using RingCentral.Subscription;

namespace RingCentralTest20160715i
{
	class MainClass
	{
		private static SubscriptionService sub;
		public static void Main(string[] args)
		{
			var sdk = new SDK("appKey", "appSecret", SDK.Server.Production);
			var platform = sdk.Platform;
			platform.Login("username", "", "password", false);
			sub = sdk.CreateSubscription();
			sub.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence?detailedTelephonyState=true");
			sub.NotificationEvent += (sender, e) => {
				Console.WriteLine("Notification: " + e.Message);
			};
			sub.Register();
			while (true)
			{ // sleep forever becase we don't want the app to quit
				Thread.Sleep(999999999);
			}
		}
	}
}
```

However, I was doing testing with my own account in production environment. I was unable to get your number working. I have no idea what the root cause is. It's mostly an environment issue or configuration issue. Please send an email to platform@ringcentral.com to ask them to help you to fix issues with your sandbox environment/account.

**Comment by addikhann** [comment]
i  was send you my Developer Credential from my side, for checking my API

**Comment by tylerlong** [comment]
@addikhann I've got your email, but it doesn't help at all. I am pretty sure that there is no problem with the C# SDK. I have justed tested at least 10 times, the same code works in production with my number but doesn't work in sandbox with your number. Apparently the root cause is your sandbox account, please send email to platform@ringcentral.com to get your sandbox account fixed.

**Comment by tylerlong** [comment]
Problem solved. I copy and paste the email for others' reference:

> The key point is you need to download the RingCentral softphone (the app) and login with your sandbox account.
> 
> Please follow these steps:
> 
> Step 1: Please read https://developers.ringcentral.com/library/tutorials/test-account.html carefully and finish the steps in “Configure Softphone for Sandbox”
> 
> Step 2: Login RingCentral for Desktop application (either windows edition or mac edition) with your sandbox account.
> 
> Step 3: Start your app(the code you wrote to receive presence notifications). Some sample code FYI:
> 
> ```cs
> private SDK sdk;
> private SubscriptionService sub;
> public void MyMethod ()
> {
>     sdk = new RingCentral.SDK ("your app key", “your app secret", SDK.Server.Sandbox);
>     sdk.Platform.Login ("your username", "", “your password", false);
>     sub = sdk.CreateSubscription ();
>     sub.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence?detailedTelephonyState=true");
>     sub.NotificationEvent += (sender, e) => {
>         Console.WriteLine(e.Message);
>     };
>     sub.Register ();
> }
> ```
> 
> Step 4. Call your number and dial extension.  Both the softphone and your app will get notifications.
> 
> 
> Please note that, you have to keep the softphone running during testing. I think this is a requirement for sandbox only. For production, you app will get notifications no matter there is softphone running or not.
> 
> P.S.  Softphone means the RingCentral for Desktop application.
>
