### ISSUE TITLE
Notification not coming up

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-csharp#54]
From user @CMCTest :

I wanted to see the notification when a new incoming call is received in the Ringcentral Desktop application.

During the notification, i have to call our aspx page to open the phone session in the CRM product.

I have used the NuGet package SDK installed in my solution, should i need to use the Client URL NuGet package in my solution? I have tried this code but notification is not coming up?

sdk = new SDK(appKey, appSecret, SDK.Server.Sandbox, "CMC CTI Test", "");
var platform = sdk.Platform;
sdk.Platform.Login(phoneNumber, "", password, false);
sub = sdk.CreateSubscription();

sub.NotificationEvent += (sender, e) => {
Console.WriteLine(e.Message);
};
sub.Register();

Can you please help me the same?

Thanks

**Comment by CMCTest** [comment]
If anyone of things can be used then why notification is not raising during the incoming call event? i have tried the sample code provided by Github and given above.

Do we have any working sample to raise the notification event from c#?

**Comment by tylerlong** [comment]
Please check the documentation http://ringcentral-csharp.readthedocs.io/en/latest/usage/notifications/Subscriptions/

In your code, you forgot to add the event filters:

```csharp
subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/message-store");
subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence");
```

For a list of all the event filters, please check: [https://developer.ringcentral.com/api-docs/latest/index.html#!#EventTypes.html](https://developer.ringcentral.com/api-docs/latest/index.html#!#EventTypes.html)

**Comment by tylerlong** [comment]
You should first test the SMS notification because it is easy to test. Once it is working, you can be sure the the notification mechanism is working and there is no issue in your code.

Incoming call notification is tricky to test in sandbox. Because it requires a softphone is running, otherwise there won't be any notifications. (production doesn't seem to have this requirement though.) Please follow the following steps to test incoming call:

1. Logon softphone with your sandbox account that you would like to test. 
    - softphone means the desktop apps for RingCentral
    - Here is the guide: https://developers.ringcentral.com/library/tutorials/test-account.html
2. Keep you softphone running and your test account logged in
3. do the test.

**Comment by CMCTest** [comment]
Thanks for the quick update.

I have tested the SMS notification and it is working fine while sending the SMS. 
I have verified your previous post reply and i have tried the same but no luck the events are not raising.

I have logged into the soft phone and soft phone was running but i could not received the notification.

**Comment by tylerlong** [comment]
The sms notifications works means there is no problem with your code.

If you followed my instructions strictly and still cannot get presence notifications working, then it's not your fault. Sometimes it just doesn't work in sandbox. If you have a production account, you can go ahead and have quick test in production. Or you can send email to devsupport@ringcentral.com to report this issue.

**Comment by CMCTest** [comment]
we are not receiving the inbound SMS notification as well, only i am able to send the SMS from my test application. I have already raised the issue with devsupport.

i have followed your previous thread and the notification is not coming up.

**Comment by tylerlong** [comment]
But you mentioned the following in your previous comment:

> I have tested the SMS notification and it is working fine while sending the SMS. 

Could you please confirm that? I am a little confused.

**Comment by CMCTest** [comment]
Sorry for the confusion, no notification is working at all.

Here is the my latest code which i was trying:

   sdk = new RingCentral.SDK(appKey, appSecret, SDK.Server.Sandbox);// SDK(appKey, appSecret, SDK.Server.Sandbox);
                 var response = sdk.Platform.Login(phoneNumber, "", password, false);
                 sub.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence");
                 sub.EventFilters.Add("/restapi/v1.0/account/~/extension/~/message-store");
                 sub = sdk.CreateSubscription();
                 
                Console.WriteLine(response);
                 
                //Console.WriteLine("Test 1 ");

                 
                 sub.ConnectEvent += (sender, args3) =>
                 {
                     Console.WriteLine("Connected:");
                     Console.WriteLine(args3.Message);
                 };
                 sub.NotificationEvent += (sender, args1) =>
                 {
                     Console.WriteLine("Notification:");
                     Console.WriteLine(args1.Message);
                 };
                 sub.ErrorEvent += (sender, args2) =>
                 {
                     Console.WriteLine("Error:");
                     Console.WriteLine(args2.Message);
                 };
                 sub.Register();

                 Console.ReadLine();

I would like to see the notification for the incoming call.

**Comment by tylerlong** [comment]
I reformat your code above.

I think the code should be changed to

```cs
sdk = new RingCentral.SDK(appKey, appSecret, SDK.Server.Sandbox);// SDK(appKey, appSecret, SDK.Server.Sandbox);
var response = sdk.Platform.Login(phoneNumber, "", password, false);

sub = sdk.CreateSubscription();
sub.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence");
sub.EventFilters.Add("/restapi/v1.0/account/~/extension/~/message-store");


Console.WriteLine(response);

//Console.WriteLine("Test 1 ");


sub.ConnectEvent += (sender, args3) =>
{
    Console.WriteLine("Connected:");
    Console.WriteLine(args3.Message);
};
sub.NotificationEvent += (sender, args1) =>
{
    Console.WriteLine("Notification:");
    Console.WriteLine(args1.Message);
};
sub.ErrorEvent += (sender, args2) =>
{
    Console.WriteLine("Error:");
    Console.WriteLine(args2.Message);
};
sub.Register();

Console.ReadLine();
```

**Comment by CMCTest** [comment]
Thanks for the response, i have tried the reformatted code which you have given unfortunately it did not worked.

No notification events are raising.

**Comment by LingForCC** [comment]
Could this be the problem with Sandbox itself again? @anilkumarbp 

Sometimes the push notification doesn't work in Sandbox environment. Have you got a production App key+secret for testing?

**Comment by CMCTest** [comment]
No we did not have the production sandbox account. If you could create it for us, i can go head and get the keys from the developer account and try the same.

Can i use the same phone number for production server as well? or will the login need to be change.

**Comment by CMCTest** [comment]
one more point, on yesterday call Vyshakh Babji showed the notification is coming up for the Java demo application what he had, but when we tested from the C# no notification is coming up.

**Comment by tylerlong** [comment]
> Thanks for the response, i have tried the reformatted code which you have given unfortunately it did not worked.

> No notification events are raising.

Did you try SMS? or you only tried incoming call? as I said it's tricky to test the latter so you should always test the former to ensure there is no problem in your code


> one more point, on yesterday call Vyshakh Babji showed the notification is coming up for the Java demo application what he had, but when we tested from the C# no notification is coming up.

There were issues in your code as shown above, so I am not suprised to know that it didn't work. But the latest code should work.

If you are still having issues, send your sample project together with your appKey, password...etc to tyler.liu@ringcentral.com and I will take a look.

**Comment by CMCTest** [comment]
I have sent the code to your email. Please check and let me know if you face any issues.

**Comment by tylerlong** [comment]
OK. It's midnight in my local time and I don't have my Windows machine with me at the moment. So I will check it tomorrow morning when I get to office. (about 9 hours later)

**Comment by tylerlong** [comment]
I have replied your email with a working demo attached. You just open the demo in Visual Studio and press F5 to run it. The appKey and password are both yours and you can see it is working:

![image](https://cloud.githubusercontent.com/assets/733544/18189664/778cac16-70ef-11e6-8e66-5c84234a384d.png)

If anybody else is interested, here is the full code (with credentials removed):

```cs
using Newtonsoft.Json;
using RingCentral;
using RingCentral.Http;
using RingCentral.Subscription;
using System;
using System.Threading;

namespace SubTest
{
    class Program
    {
        private SDK sdk;
        private SubscriptionService subscription;

        public void SetupSub()
        {
            sdk = new SDK("appKey", "appSecret", SDK.Server.Sandbox, "SubTest", "1.0.0");
            sdk.Platform.Login("number1", "", "password", true);

            subscription = sdk.CreateSubscription();
            subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/message-store");
            subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence");
            var connectCount = 0;
            subscription.ConnectEvent += (sender, args) => {
                connectCount += 1;
                Console.WriteLine(args.Message);
            };
            var messageCount = 0;
            subscription.NotificationEvent += (sender, args) => {
                messageCount += 1;
                Console.WriteLine(args.Message);
            };
            var errorCount = 0;
            subscription.ErrorEvent += (sender, args) => {
                errorCount += 1;
                Console.WriteLine(args.Message);
            };
            subscription.Register();
            SendSMS();
            Thread.Sleep(15000);
            SendSMS();
            Thread.Sleep(15000);
            subscription.Remove();
            Console.WriteLine(connectCount);
            Console.WriteLine(messageCount);
            Console.WriteLine(errorCount);
            Console.ReadLine();
        }

        private void SendSMS()
        {
            var requestBody = new
            {
                text = "hello world",
                from = new { phoneNumber = "number1" },
                to = new object[] { new { phoneNumber = "number2" } }
            };
            var request = new Request("/restapi/v1.0/account/~/extension/~/sms", JsonConvert.SerializeObject(requestBody));
            sdk.Platform.Post(request);
        }

        static void Main(string[] args)
        {
            var program = new Program();
            program.SetupSub();
        }
    }
}
```

**Comment by CMCTest** [comment]
Thanks for the update. Sending the SMS is working fine in our test app as well.

problem is when we make the incoming call we are not receiving the notification.

Could you please check the Ringcentral desktop application with the same phone credentials and let me know if you are receiving the connected event?

**Comment by tylerlong** [comment]
I am sorry but I didn't have a chance to try it yet. For presence event, there is the detailed instruction at the bottom of https://github.com/ringcentral/ringcentral-csharp/issues/50

Please be aware that presence event from sandbox is unstable. Sometimes it just doesn't work. I have no good way to overcome it but you can always report issue to devsupport@ringcentral.com and tell them sms notification is working while presence event is not working. It's out of the scope of this C# SDK project to solve the problem because the root cause resides on platform side.

**Comment by tylerlong** [comment]
I tested today and I confirm that incoming call is working as well.

![image](https://cloud.githubusercontent.com/assets/733544/18236493/14607052-7359-11e6-995e-92f1bc4fd3f5.png)


I registered all the event filters:

```cs
subscription = sdk.CreateSubscription();
subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/message-store");
subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/message-store/instant?type=SMS");
subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence");
subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence/line/presence");
subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence?detailedTelephonyState=true");
subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence/line/presence?detailedTelephonyState=true");
subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence/line");
```

And seems that `` works.

**Comment by CMCTest** [comment]
Thank you for your help, it is working fine now. I do have a one more question regarding the extensions?

Is there any way to register all the extension with out using the extension ID?

Currently, i am using the this 2 extension id adding into the filter, based on the documentation, it is looks like we need to hard code the extension ID in the filter to subscribe.

 subscription.EventFilters.Add("[/restapi/v1.0/account/~/extension/138705004/presence. " + "/restapi/v1.0/account/~/extension/138797004/presence]");

This will make additional to request call the extension API and get all the list of extension and adding it one by one.

I would like to know is there any easy method to subscribe all the extension id? even the extension is not active will it possible to add all the extensions in the filter?

**Comment by tylerlong** [comment]
Could you please create a new issue instead? Because your last question is not about "Notification not coming up" any more and it will cause confusion to other readers.

**Comment by ashitvora** [comment]
Does RingCentral support Webhook notifications?

**Comment by grokify** [comment]
Yes, webhooks are supported. Here's some information to get you started:

* Docs: http://ringcentral-api-docs.readthedocs.io/en/latest/webhooks/
* Instant SMS Event: https://devcommunity.ringcentral.com/ringcentraldev/topics/can-i-retrieve-the-contents-of-an-inbound-text-message-via-push-notifications-using-the-subscription-api
