### ISSUE TITLE
Subscribing and Adding Filter for all the extension

### ISSUE THREAD

**Issue by CMCTest** [ringcentral/ringcentral-csharp#56]
Thank you for your help, it is working fine now. I do have a one more question regarding the extensions?

Is there any way to register all the extension with out using the extension ID?

Currently, i am using the this 2 extension id adding into the filter, based on the documentation, it is looks like we need to hard code the extension ID in the filter to subscribe.

subscription.EventFilters.Add("[/restapi/v1.0/account/~/extension/138705004/presence. " + "/restapi/v1.0/account/~/extension/138797004/presence]");

This will make additional to request call the extension API and get all the list of extension and adding it one by one.

I would like to know is there any easy method to subscribe all the extension id? even the extension is not active will it possible to add all the extensions in the filter?

**Comment by tylerlong** [comment]
Here is the doc for your question: http://ringcentral-csharp.readthedocs.io/en/latest/usage/notifications/Subscriptions/

Please scroll to the bottom and you will see the answer.

Let me elaborate here:

First call endpoint `/restapi/v1.0/account/~/extension` to get a list of all the extensions. Let's say you store the extension IDs in an array like this `var extIDs = new string[] { "111", "222", "333", "444", ... }`.

Then you can subscribe to all the extensions:

```cs
foreach(var id in extIDs) 
{
    sub.EventFilters.Add(string.Format("/restapi/v1.0/account/~/extension/{0}/presence?detailedTelephonyState=true", id));
}
```

I wrote the code above outside of Visual Studio so it might not compile but you can get the idea.

**Comment by CMCTest** [comment]
It worked now. Thanks for your help.
