### ISSUE TITLE
Call Disconnect operation

### ISSUE THREAD

**Issue by CMCTest** [ringcentral/ringcentral-csharp#58]
During the call disconnect notification i did not received the call start time or end time and duration?

Do we need to raise the Call log request to get these information for each call? do we have any method which are available to get these details with out calling the call log rest API?

**Comment by tylerlong** [comment]
You are right, there is no duration information in disconnect notification and you have to raise call log request. There is no better way that I am aware of.

**Comment by CMCTest** [comment]
Could you please provide any samples for this request? Specific to getting the phone number details, Call Start time, Call End time and Duration of the call.

**Comment by tylerlong** [comment]
So are you having any issues? Could you please show me your code or error messages?

**Comment by CMCTest** [comment]
OK, i can manage this request by custom solution, i would not want to make another request and get the disconnect details and process the same. It would take time in our application to display the data.
