### ISSUE TITLE
Subscription expiring after couple of hours using c#SDK version 1.0.0

### ISSUE THREAD

**Issue by shashank0764** [ringcentral/ringcentral-csharp#61]
hello team,

i have posted my issue on the dev community, please see the link below.

https://devcommunity.ringcentral.com/ringcentraldev/topics/sms-subscription-is-not-working-after-couple-of-hours

**Comment by tylerlong** [comment]
I don't know why but I cannot access the link you posted

![image](https://cloud.githubusercontent.com/assets/733544/19231559/37e08902-8f0d-11e6-9495-6ad7606b71bd.png)

I have logged in.

@bdeanindy  thoughts?

**Comment by shashank0764** [comment]
ok, so i am using c# sdk ver 1.0.0 to subscribe for incoming sms and also calls. for now i am posting the code for sms. even though the subscriotion works after some time the notifications don't show up. once restarted the application it starts working.  below is the code.
`private SDK sdk;        private SubscriptionService subscription;

        public void SetupSub()
        {
           
          
            Logger.TraceLog(System.Diagnostics.TraceEventType.Information, "SetupSub", "*********************************Function Started*************************");
            string appsecret = ConfigurationManager.AppSettings["appsecret"];
            string appkey = ConfigurationManager.AppSettings["appkey"];
            string userphonenumber = ConfigurationManager.AppSettings["userphonenumber"];
            string password = ConfigurationManager.AppSettings["password"];
            string defaultendpoint = ConfigurationManager.AppSettings["apiendpoint"];
            string fromnumber = ConfigurationManager.AppSettings["fromnumber"];

            sdk = new SDK(appkey,appsecret, defaultendpoint, "IncomingSMSapp", "1.0.0");
            sdk.Platform.Login(userphonenumber, "", password, true);
            Logger.TraceLog(System.Diagnostics.TraceEventType.Information,"Info", "Subscription successful");
            subscription = sdk.CreateSubscription();

            subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/message-store/instant?type=SMS");
            var connectCount = 0;
            subscription.ConnectEvent += (sender, args) => {
                connectCount += 1;
               // Console.WriteLine(args.Message);
                Logger.TraceLog(System.Diagnostics.TraceEventType.Information, "Info", "Connected");
            };
            var messageCount = 0;
            subscription.NotificationEvent += (sender, args) => {
                messageCount += 1;
               // Console.WriteLine(args.Message);
                Logger.TraceLog(System.Diagnostics.TraceEventType.Information, "Info", "Incoming SMS  Notification received," + args.Message.ToString());

                var obj = JObject.Parse(args.Message.ToString());
              string messagecontent= obj.AsJEnumerable()["body"]["subject"].ToString();
              messagecontent = messagecontent.Replace("#", "%23");
              Logger.TraceLog(System.Diagnostics.TraceEventType.Information, "Info", "Incoming SMS  Notification received, message" + messagecontent);
              string from=obj.AsJEnumerable()["body"]["from"]["phoneNumber"].ToString();
              Logger.TraceLog(System.Diagnostics.TraceEventType.Information, "Info", "Incoming SMS  Notification received, From" + from);
              string to = obj.AsJEnumerable()["body"]["to"][0].ToString().Split(':')[1].Split('"')[1];
              from = from.Remove(0, 1);
              Logger.TraceLog(System.Diagnostics.TraceEventType.Information, "Info", "Incoming SMS  Notification received, To" + to);
              Logger.TraceLog(System.Diagnostics.TraceEventType.Information, "Info", "Incoming SMS  Notification received, To" + from);
             
            };
            var errorCount = 0;
            subscription.ErrorEvent += (sender, args) => {
                errorCount += 1;
               // Console.WriteLine(args.Message);
                Logger.TraceLog(System.Diagnostics.TraceEventType.Information, "Info", "Incoming SMS  Error received," + args.Message);
            };
            subscription.Register();
            Logger.TraceLog(System.Diagnostics.TraceEventType.Information, "Info", "Subscribed successfully");
            
                Logger.TraceLog(System.Diagnostics.TraceEventType.Information, "Info", "Thread", "Waiting for incoming sms events");
            `
Please help

**Comment by tylerlong** [comment]
From the code snippet you posted, it's hard to tell if `sdk` and `subscription` will be garbage collected during the whole lifecycle of your app. Could you please make sure that they are global variables and will never be garbage collected?  If this doesn't solve the issue, could you please send the whole sample project to tyler.liu@ringcentral.com ? I would like to have a try.

**Comment by shashank0764** [comment]
ok i just emailed the sample project.

**Comment by CMCTest** [comment]
Hi Tyler,

Any updates on this issue?

Thanks for your help!!

**Comment by tylerlong** [comment]
Hi @CMCTest , now it is morning in my local time and I am looking into it.  Please stay tuned.

**Comment by tylerlong** [comment]
Quick update:

I think you should add `Console.ReadLine();` to the end of the `Main` method. Otherwise, the whole program will quit after `program.SetupSub();` and everything will be garbage collected.

Or Please try with a WPF project which won't quit until you click the close button of the window.

Keep me updated.

**Comment by shashank0764** [comment]
Hello Tyler ,

I tried with the console.readline() but the result is same. even if the service is running the notifications don't show up after couple of hours. I was thinking to restart the service every 2 hour using the code so that this issue can be fixed. do you think it is a good idea or can you suggest any thing else?

**Comment by tylerlong** [comment]
It is a bug if it's reproducible

You can try this https://github.com/ringcentral/ringcentral-csharp/blob/master/RingCentral/Subscription/SubscriptionService.cs#L74 Every 1-2 hours call this method to refresh the subscription manually.

**Comment by tylerlong** [comment]
Close it since it has been inactive for very long time.

Let me summarize it: normally the subscription is auto-refreshed and will never expire. But you can also call `rc.Register` manually.
