### ISSUE TITLE
Which Visual Studio Project Type works best for this SDK?

### ISSUE THREAD

**Issue by jmol123** [ringcentral/ringcentral-csharp#63]
Hi there,

I am confused as to which Project Type to pick in Visual Studio for this SDK.  The program I will write will not require any UI and will operate entirely headlessly.  The plan is to have it run all the time and download faxes as soon as they come in to the server hosting the program.

Has anyone done this before, or have any advice for me?

Thanks!!

**Comment by tylerlong** [comment]
Choosing a project type is out of the scope of this project and it solely depends on your business requirement and your expertise.

If you don't need UI then a console project should be sufficient. 

You can monitor fax with subscription  http://ringcentral-csharp.readthedocs.io/en/latest/usage/notifications/Subscriptions/

**Comment by tylerlong** [comment]
By the way, you can also use this project: https://github.com/ringcentral/ringcentral-csharp-client

It provides samples for subscription and fax downloading:

https://github.com/ringcentral/ringcentral-csharp-client/blob/master/RingCentral.Test/SubscripotionTest.cs#L31

https://github.com/ringcentral/ringcentral-csharp-client/blob/master/RingCentral.Test/BinaryTest.cs#L62
