### ISSUE TITLE
Error: Unauthorized for this grant type

### ISSUE THREAD

**Issue by ManojMali0807** [ringcentral/ringcentral-csharp#70]
Hi,

I am using this package in Web app & I am getting below error;

 "Message": "An error has occurred.",
    "ExceptionMessage": "Unauthorized for this grant type",
    "ExceptionType": "RingCentral.Http.ApiException"

My Code is:
`// Initialize Ring Central Client
            SDK sdk = new SDK("qLgryAnJQJuOANOBKjm1kg"
                ,"5P5yZZKlQPeE8ccvGrhRFw6gNhPCYhRrWOWSVfcHh74g"
                , "https://platform.devtest.ringcentral.com"
                , "CPO"
                , "1.0.0.0");

            var platform = sdk.GetPlatform();

            // Password Grant Authorization
            Response response = platform.Authorize("+13128589837", "101", "Developer123", true);`

Please help me out.
I have created sandbox account on developer.ringcentral.

**Comment by tylerlong** [comment]
Please check this: https://devcommunity.ringcentral.com/ringcentraldev/topics/http-400-unauthorized-for-this-grant-type

Feel free to create a new issue if it doesn't work for you.
