### ISSUE TITLE
Double Uri encoding for password

### ISSUE THREAD

**Issue by mkoval-ua** [ringcentral/ringcentral-csharp#8]
e.g. password char `<` is passed as `%253C` instead of just `%3C`

So probably you don't need to escape password string as it causes double encoding:

`{"password", Uri.EscapeUriString(password)} =>  {"password", password}`

It seems that there is another escaping when JSON is converted into HTTP query string

**Comment by mkoval-ua** [comment]
One more comment - my password contains char "<" and then char ":". It's quite strange but first one is double-encoded while second one encoded just once (%3A) !

**Comment by grokify** [comment]
This has been fixed by removing `Uri.EscapeUriString()` and pushed as version 0.1.1 to Nuget.

Thanks!

**Comment by mkoval-ua** [comment]
Thank you a lot for the fix as well as for the great sdk!
